### ISSUE TITLE
[FEATURE] Translate to Brazilian Portuguese PT-BR

### ISSUE THREAD

**Issue by TheNeoCarvalho** [octokatherine/readme.so#127]
Hi, I would like to translate it into Brazilian Portuguese.

**Comment by waldyrious** [comment]
@TheNeoCarvalho there's already work in progress for this — see #72, and the associated PR, #73.

**Comment by waldyrious** [comment]
@katherinepeterson this issue is a duplicate of #72, so it can be closed as well.
