### ISSUE TITLE
Drop down menu for sections

### ISSUE THREAD

**Issue by smortezah** [octokatherine/readme.so#133]
It could be great if the sections to be added were listed in a drop down menu, for easier accessibility.

**Comment by MicahBCode** [comment]
This is a duplicate of #85 and may be closed.

**Comment by daacode** [comment]
Can I work on this?

**Comment by octokatherine** [comment]
@daacode yes, do you still want to work on it?

**Comment by daacode** [comment]
Hi @octokatherine, definitely I still want to work on it
