### ISSUE TITLE
Editor sits in "Loading" mode...

### ISSUE THREAD

**Issue by weisisheng** [octokatherine/readme.so#137]
Using latest versions of chrome and ffox, yarn dev launches the app but I can't use it since the Editor window displays "Loading..." message and blocks further interaction.  Would appreciate any advice or trailheads.

Thanks in advance.

**Comment by octokatherine** [comment]
@weisisheng please let me know if you still experience this. I am closing the issue for now because I can't reproduce it and haven't heard of another occurrence
