### ISSUE TITLE
Suggested integration: SimpleLocalize CLI

### ISSUE THREAD

**Issue by jpomykala** [octokatherine/readme.so#138]
Hey I saw on the project on Reddit. You might me interested in managing translations using SimpleLocalize with a special account for open-source projects. I could configure a pipeline to automatically upload translations and translation keys from the project and download them before a deployment. Then we could share a public link for translators. 🙂

Let me know if you are interested, so I can start working on the integration!

**Comment by katherinepeterson** [comment]
@jpomykala that sounds great!

**Comment by jpomykala** [comment]
Cool, I will configure it then, probably in next week!
