### ISSUE TITLE
"BuyMeACoffe" icon not appear at first time

### ISSUE THREAD

**Issue by diegocanepa** [octokatherine/readme.so#158]
The first time that I redirect to the site, BuyMeACofe icon doesn't appear. Then, if I reload/refresh the page, the icon appears.
I took a picture of the difference.

![image](https://user-images.githubusercontent.com/48829737/120908559-cc700780-c641-11eb-8167-7823d3805fa4.png)
![image](https://user-images.githubusercontent.com/48829737/120908563-d265e880-c641-11eb-93aa-8060168978a4.png)

**Comment by omegatrix** [comment]
Hi @diegocanepa please may I claim this to work on? It'd be my first open source contribution :)

**Comment by diegocanepa** [comment]
> Hi @diegocanepa please may I claim this to work on? It'd be my first open source contribution :)

**Comment by diegocanepa** [comment]
Sorry, I close the issue for a mistake. Yes, obviously, you can correct the bug. 
No problem with that.
