### ISSUE TITLE
Feature: Cache

### ISSUE THREAD

**Issue by bacarpenter** [octokatherine/readme.so#164]
Hey! I just spent about 20 mins working on a README and accidentally reloaded the page. All my work was lost. Could a cache be implemented so that work is saved briefly to cut down on these accidents?

Love the site.

Ben

**Comment by priyanshk20** [comment]
Can I work on this issue please?

**Comment by octokatherine** [comment]
@priyanshk20 yes please!

**Comment by priyanshk20** [comment]
Sure! Working on it.

**Comment by priyanshk20** [comment]
@octokatherine This issue is with "react-markdown". 
I have asked a solution for this issue in their Q&A discussion page. I will figure it out, once someone helps me out from their side. Is that okay?
Can I work on other issues till then?

**Comment by octokatherine** [comment]
@priyanshk20 what was the issue? Can you link me to the discussion page?
