### ISSUE TITLE
New Section Table of Content with Heading and SubHeading

### ISSUE THREAD

**Issue by daniloab** [octokatherine/readme.so#168]
It would be nice to add a new section called `Table of Content` like the example below:

```md
- [1. Introduction](#1-introduction)
  * [1.1 Purpose](#11-purpose)
  * [1.2 Scope](#12-scope)
  * [1.3 Acronyms](#13-acronyms)
  * [1.4 References](#14-references)
    + [1.4.1 Internal References](#141-internal-references)
    + [1.4.2 External References](#142-external-references)
  * [1.5 Overview](#15-overview)
``` 

I'll push a pr that adds this new section.

If already exist, please tell me, instead let's improve this amazing tool! Thanks @octokatherine

**Comment by octokatherine** [comment]
I actually think if we were to add a Table of Contents, I would want to make it automatically generated based on the other sections added. However, I don't think it's needed right now because Table of Contents on Readme files are now a built in feature on GitHub.

**Comment by Avivhdr** [comment]
I can't believe I discover it only now...
![table of content](https://user-images.githubusercontent.com/23265867/143676031-553f5eed-f752-4697-a680-9ded4e312441.gif)
