### ISSUE TITLE
Make readme.so a PWA

### ISSUE THREAD

**Issue by max-programming** [octokatherine/readme.so#187]
I was thinking about making readme.so a PWA which can even run offline. Using the `nest-pwa` package,

Assign this issue to me if you would like me to do it @jose-vale

**Comment by jose-vale** [comment]
> I was thinking about making readme.so a PWA which can even run offline. Using the `nest-pwa` package,
> 
> Assign this issue to me if you would like me to do it @jose-vale

I'm not the owner of the repo, you need to ask @octokatherine.

**Comment by max-programming** [comment]
I mean you are one of the collaborators right?

**Comment by jose-vale** [comment]
> I mean you are one of the collaborators right?

I have contributed to the repo yes, but I do not have those permissions.

**Comment by max-programming** [comment]
Okay, I get it! I'll wait no problems 👍

**Comment by octokatherine** [comment]
@max-programming sounds great to me, go for it!

**Comment by max-programming** [comment]
On it 🔥 !

**Comment by max-programming** [comment]
@octokatherine The above pull request closes this issue 🙂
