### ISSUE TITLE
Deleting a section does not clear changes

### ISSUE THREAD

**Issue by jose-vale** [octokatherine/readme.so#189]
See attached gif. Will work on the fix. 

![example](https://user-images.githubusercontent.com/57798333/128445854-b7fdb665-e79a-48a1-bd68-a7cd0e641588.gif)

**Comment by octokatherine** [comment]
I'm honestly not sure what the expected behavior would be here. My concern with this is a user accidentally clicking the trash icon and losing their work

**Comment by jose-vale** [comment]
That's a good point. Do you think that it would be a better experience if the state was maintained on delete, but next to the delete button there was a restore option?
Currently the only way to get the original templates is to do a full reset.

**Comment by octokatherine** [comment]
I like that idea! I think we should add the reset circular arrow (same icon as above) next to the delete icon, and make sure it asks for confirmation before resetting the section

**Comment by jose-vale** [comment]
Will add that icon as discussed as soon as I can.

**Comment by jose-vale** [comment]
@octokatherine I implemented the discussed changes, let me know if there is anything you don't agree with.
