### ISSUE TITLE
Add emoji support for preview

### ISSUE THREAD

**Issue by juancwu** [octokatherine/readme.so#213]
It would be really nice to be able to see the actual emoji on the preview tab. Although it is not the biggest deal, it is nice to have it there. I would love to make a PR for this feature as well. Let me know if that is possible!

**Comment by allister-grange** [comment]
I can see emoji's in the preview, is there something that I am missing here?

![image](https://user-images.githubusercontent.com/18430086/141737050-0ebf177d-fa0a-4f0d-990a-696351c5dc29.png)

**Comment by octokatherine** [comment]
@allister-grange great question, I actually didn't try it.

@juancwu was there something specific that wasn't rendering for you?

**Comment by juancwu** [comment]
@octokatherine @allister-grange , the functionality I was looking for was directly typing something like `:tada:` to render an emoji, in this case it would be 🎉. I have been quite busy so I haven't really started to implement this.

**Comment by juancwu** [comment]
Sorry, I haven't got my hands down to work on this feature. I do not think I will have the time to do so anytime soon, so I will close this issue.
