### ISSUE TITLE
Feature Request: Ability to support Todo list

### ISSUE THREAD

**Issue by homfarnam** [octokatherine/readme.so#224]
Hi, I searched a few days ago about adding a todo list to my README file, and finally I found that, and I did that.
I thought that it would be great if I can add this feature to the project because before searching, I wanted to use your product and I didn't find that. 
What do you think?

**Comment by octokatherine** [comment]
When you say "adding a to do list", what do you mean? A section called "To Do List" or are you talking about rendering checkboxes?

**Comment by homfarnam** [comment]
I mean checkboxes, right. 
something like this

![Screen Shot 2021-11-19 at 7 44 51 PM](https://user-images.githubusercontent.com/20749734/142655533-3c1daab3-c3f5-4639-8dc5-a148ccafe5fe.png)

**Comment by octokatherine** [comment]
hm, it should already render that way,  you just have to type `- [ ]`

**Comment by homfarnam** [comment]
Yeah, but I thought that It could be useful.

**Comment by octokatherine** [comment]
I think I'm confused about what exactly you're suggesting because it seems like that functionality already exists

**Comment by suhaasya** [comment]
I think he wants a to-do list section tab in the sections.

**Comment by octokatherine** [comment]
I think I'm going to close out this issue

> I think he wants a to-do list section tab in the sections.

If this is the case, I would recommend using the new Custom Section feature
