### ISSUE TITLE
Feature Request: Finish Portuguese support

### ISSUE THREAD

**Issue by gustavothecoder** [octokatherine/readme.so#229]
**Is your feature request related to a problem? Please describe.**
The editor's page is not fully translated into Portuguese, so the site are less accessible for those who only speak Portuguese.

**Describe the solution you'd like**
We can finish the translation, by the way, I can do that.

**Comment by octokatherine** [comment]
@gustavothecoder if you want to take this up, that would be great! I'll assign you
