### ISSUE TITLE
Red highlight in API endpoint in API references 

### ISSUE THREAD

**Issue by Arpitjs** [octokatherine/readme.so#240]
**Describe the bug**
The title of the API endpoint in API references has a red highlighting

**To Reproduce**
This behavior is not seen in readme.so but seen when pushed to github,

**Expected behavior**
The red highlight should be removed.

**Screenshots**
![err](https://user-images.githubusercontent.com/53225448/163042463-7fb1e189-c86a-4886-b61e-74d011acd4d3.png)

**Comment by octokatherine** [comment]
```http
  GET /api/items/${id}
```

^ looks like it happens when you put http as the language for the code block. happy to just remove that

**Comment by Arpitjs** [comment]
thank you, closing the issue :)
