### ISSUE TITLE
Bug: Editor don't work

### ISSUE THREAD

**Issue by wuwenrufeng** [octokatherine/readme.so#246]
**Describe the bug**
I first open this site,but Editor window displays "Loading..." , I havn't opreator else.

**To Reproduce**
open site readme.so

**Screenshots**
![image](https://user-images.githubusercontent.com/45844514/168986603-878639bd-db31-4cd9-bff4-04a5ffa2598a.png)

**Additional context**
chrome Version 96.0.4664.93 (Official Build) (x86_64)

**Comment by octokatherine** [comment]
@wuwenrufeng is this still happening? I can't repro

**Comment by TheGarious** [comment]
Can you share your console browser output ?
