### ISSUE TITLE
Bug: dark mode in preview ruins display of emoji and color

### ISSUE THREAD

**Issue by yipei1028** [octokatherine/readme.so#247]
**Describe the bug**

**To Reproduce**

1. Go to [editor](https://readme.so/editor)
2. Click on dark/light mode switcher
3. See as following: Emojis display with weird filter and color code display incorrectly
![image](https://user-images.githubusercontent.com/23658455/174471136-51af661c-3451-4876-b175-692e662bba42.png)

**Expected behavior**
Emojis and color code should be consistent under both dark mode and light mode.
![image](https://user-images.githubusercontent.com/23658455/174471152-477dc4a6-a9f8-49e9-b14a-bcebb19f6f98.png)

**Screenshots**
 NA

**Additional context**
NA

**Comment by yipei1028** [comment]
I looked into the implementation of mode switching. Using `filter: invert(0.9)` is handy but come with some drawbacks.
I would love to make a PR for enhancing this one. Let me know if that is possible!

**Comment by octokatherine** [comment]
@yipei1028 feel free to open a PR with a fix! thanks!

**Comment by yipei1028** [comment]
Hi @octokatherine,
Just open a pull request for this issue: https://github.com/octokatherine/readme.so/pull/281. Please take a look :)
