### ISSUE TITLE
Bug:  Styling of sponsor button is not proper

### ISSUE THREAD

**Issue by Abjcodes** [octokatherine/readme.so#252]
**Describe the bug**
The sponsor button is showing black edges all over the sides

**To Reproduce**

1. Go to 'homepage'
2. Click on 'the sponsor button'
3. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/42151354/182221427-9b5ab1ce-2381-43b7-838d-9d25ee607b4d.png)

**Comment by octokatherine** [comment]
Thanks, closing this out because it's actually an issue on GitHub's side
