### ISSUE TITLE
Bug:  MIT license badge shows up as "inaccessible"

### ISSUE THREAD

**Issue by SumitNalavade** [octokatherine/readme.so#253]
**Describe the bug**
The MIT license badge shows up as "inaccessible"

**To Reproduce**

1. Go to 'https://readme.so/editor'
2. Click on 'Badges'

**Expected behavior**
The badge should show up as "MIT"

**Screenshots**
![Screen Shot 2022-08-03 at 12 16 25 AM](https://user-images.githubusercontent.com/48499839/182530722-ea1cc290-8386-4682-9cb8-7a515b8f290d.png)

**Comment by SumitNalavade** [comment]
I can open a PR to fix the link if that's ok.

**Comment by octokatherine** [comment]
@SumitNalavade that would be great!
