### ISSUE TITLE
Bug: Uneven black border around the "sponsor" button on the homepage.

### ISSUE THREAD

**Issue by itsmenikhill** [octokatherine/readme.so#261]
On the homepage of the website, around the sponsor button there is a black border that is smaller on the top and bigger on the bottom.

1. Go to 'https://readme.so/'
2. See error

![image](https://user-images.githubusercontent.com/44477975/191016198-9728b667-6065-48be-823f-7b018eff0533.png)

**Comment by MicahBCode** [comment]
Could you please specify your Browser version?

**Comment by itsmenikhill** [comment]
Google Chrome Version 105.0.5195.127

**Comment by MicahBCode** [comment]
I've just tested the page with Chrome version 105. Unable to reproduce. Issue may be closed @octokatherine

**Comment by codemasters2624** [comment]
@MicahBCode Issue still persists as of today. My Chrome browser version is 99.0.4844.51 and I can see it in the above mentioned page.

**Comment by alexwiench** [comment]
Also present in Firefox 105.0.1

The background of the embedded iframe matches your system theme. This is why some people see it an some don't. I'm not sure what the advantage of putting the button in an iframe is.
