### ISSUE TITLE
Feature Request: The text wrap feature

### ISSUE THREAD

**Issue by anirudhahavaldar** [octokatherine/readme.so#266]
**Is your feature request related to a problem? Please describe.**
Feature request is not a problem, but a need. The text wrap feature is most important in any text editor. 

**Describe the solution you'd like**
There should be an option for text wrap as we get in the readme editor of GitHub.

**Describe alternatives you've considered**
Nope

**Additional context**

**Comment by octokatherine** [comment]
@anirudhahavaldar done!
