### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by AYassin01** [octokatherine/readme.so#285]
**Describe the bug**
The editor window doesn't show anything.

**To Reproduce**

1. Click on 'Get Started'
2. Try to add a new section
3. You'll see the Editor window is showing nothing but 'loading'

**Screenshots**

![08 07 2023_15 41 37_REC](https://github.com/octokatherine/readme.so/assets/106158907/566fc05a-21e7-4968-9c39-1f5bfe02bace)

**Comment by AYassin01** [comment]
@koji can you help with that?

**Comment by Amar2Kk** [comment]
same issue

**Comment by AYassin01** [comment]
Here is how I solved the issue: 1- Simply try to use another browser (ex: Chrome) 
                                                  2- If not, then use a VPN
