### ISSUE TITLE
Drag and dropping sections doesn't work properly (Firefox 87.0, MacOS)

### ISSUE THREAD

**Issue by martinlbrook** [octokatherine/readme.so#32]
Rather than dragging the section button, the drag handle icon is picked up instead. When this is released, I can move the session normally.

Video demonstration:

https://user-images.githubusercontent.com/572323/114386390-129c7380-9b89-11eb-88c4-d944e679a00a.mov

### Version info

Firefox 87.0
MacOS Big Sur 11.2.3 (20D91)

**Comment by katherinepeterson** [comment]
@martinlbrook thanks for reporting this! someone else said that the editor wasn't loading on firefox also, have you seen that?
