### ISSUE TITLE
Add section templates for GitHub profile readmes

### ISSUE THREAD

**Issue by octokatherine** [octokatherine/readme.so#34]

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson , would like work on this feature . Basically this is about having a profile portfolio readme.md right , like the one here https://github.com/abhisheknaiidu/awesome-github-profile-readme ?

**Comment by katherinepeterson** [comment]
@saurabhchaturvedy yes, exactly! it's just adding more sections
