### ISSUE TITLE
Make site responsive for mobile

### ISSUE THREAD

**Issue by octokatherine** [octokatherine/readme.so#4]
Currently, on any touch devices, when you navigate to the editor it just shows a message saying that this site is optimized for desktop.

**Comment by Rishabh-Rathod** [comment]
Hi @katherinepeterson, I would like to work on this issue. Is there a basic mobile responsive layout designed ? or can i suggest/submit design idea.

**Comment by katherinepeterson** [comment]
@Rishabh-Rathod feel free to submit an idea!

**Comment by michaelnji** [comment]
Hi @katherinepeterson I would love to work on this issue too! Ive got some basic mobile designs (from my other projects) which could apply to this project to (with some tweaking)

**Comment by Rishabh-Rathod** [comment]
Hi @michaelnji,

Can you share your idea screenshots, 

what i have thought was
1. Toggleable Side drawer for sections. 
2. Horizontal Tabs for Editor and Previewer.

If your idea is similar we can divide tasks and contribute.

**Comment by Rishabh-Rathod** [comment]
@katherinepeterson 

> 1. Toggleable Side drawer for sections.
> 2. Horizontal Tabs for Editor and Previewer.

i have modified css to showcase below design idea, real implementation will have drawer icon and better UI.

1. Opening **sections** in side drawer - 

![Screenshot 2021-04-23 at 11 10 07 PM](https://user-images.githubusercontent.com/23132741/115910756-dc18ff80-a48a-11eb-84a5-4d13b550ffde.png)


2. Horizontal tabs for editor, preview and raw (same header as above)
![Screenshot 2021-04-23 at 11 21 20 PM](https://user-images.githubusercontent.com/23132741/115910766-de7b5980-a48a-11eb-94ed-44db477925da.png)

**Comment by katherinepeterson** [comment]
> @katherinepeterson
> 
> let me know your feedback on the idea and then i would proceed to implement it.
> 
> > Disclaimer - i have modified css to showcase below design idea, real implementation will have drawer icon and better UI.
> 
> 1. Opening **sections** in side drawer -
> 
> ![Screenshot 2021-04-23 at 11 10 07 PM](https://user-images.githubusercontent.com/23132741/115910756-dc18ff80-a48a-11eb-84a5-4d13b550ffde.png)
> 
> 1. Horizontal tabs for editor, preview and raw (same header as above)
>    ![Screenshot 2021-04-23 at 11 21 20 PM](https://user-images.githubusercontent.com/23132741/115910766-de7b5980-a48a-11eb-94ed-44db477925da.png)

I think that looks pretty good. On screenshot 2 I might right align the Preview and Raw so they are visually separate from the Editor. (the editor only shows the currently selected section whereas the others show the whole readme. might be unclear.

**Comment by Rishabh-Rathod** [comment]
> On screenshot 2 I might right align the Preview and Raw so they are visually separate from the Editor. (the editor only shows the currently selected section whereas the others show the whole readme. might be unclear.

Got it. Will take care of that while coding it.

**Comment by Rishabh-Rathod** [comment]
i am noting down changes to be done and also status of my development.

- [x] Toggle Drawer containing `sections`.
- [ ] Fix `section` item's drag and drop functionality for mobile.
- [ ] Implement Tabs to show column selection. ( screenshot 2 for reference )
   - [ ] separation of header UI from EditorColumn and PreviewColumn component to reuse code for tabs.
- [ ] limit maxWidth of PreviewColumn to avoid its overflow outside the viewport.

**Comment by katherinepeterson** [comment]
@Rishabh-Rathod thanks for working on this, it's been a highly requested feature! 

I wanted to let you know if you didn't already that the monaco editor doesn't work on mobile, so you'll have to replace it with a normal text editor on mobile

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod thanks for working on this, it's been a highly requested feature!
> I wanted to let you know if you didn't already that the monaco editor doesn't work on mobile, so you'll have to replace it with a normal text editor on mobile

hey @katherinepeterson, thanks for reminding me, i totally forgot about that. 

Also, i had a small query. 
for making a common Navigation Bar for `EditorColumn` and `PreviewColumn` in mobile i will need to bring the state of those component to parent component. 
for that I am creating another component to wrap `EditorColumn` and `PreviewColumn` where i maintain state.
This will lead to propDrilling from `editor.js` -> `EditPreviewContainer.js` -> `( EditorColumn.js / PreviewColumn.js )`

Is 2 layer propDrilling fine ? or shall i maintain state in context to avoid propDrilling?

**Comment by katherinepeterson** [comment]
@Rishabh-Rathod im okay with the two level prop drilling here
