### ISSUE TITLE
Suggested Feature : Add emoji Support 

### ISSUE THREAD

**Issue by dnmanor** [octokatherine/readme.so#75]
Hey @katherinepeterson , pretty trivial feature but I think it will be nice to support adding markdown emojis within the app as I've noticed  that quite a number of READMEs have them (including some of mine haha).  Let me know what you think, thank you.

**Comment by katherinepeterson** [comment]
@dnmanorr so I believe emojis do currently work if you paste them in or use the cmd ctrl space shortcut on a mac.

Are you referring to being able to use the `:emoji:` syntax?

**Comment by dnmanorr** [comment]
@katherinepeterson yes, they do work when you copy and paste them. On windows ` Window key + ;` . But the same way you click on a tab and it inserts directly a template into your editor, I thought it'd be nice to have one for emojis. You click an emoji and it adds `:emoji:` to your file without having to use shortcuts or copy & paste.

**Comment by ndom91** [comment]
Yeah what do you guys/gals think about maybe having a toggle where you can enable / disable pre selected emojis next to the section titles in their respective headers. 

I.e. https://github.com/newtelco/newtelco-dato
![image](https://user-images.githubusercontent.com/7415984/117067131-ea3c0b00-ad29-11eb-9fa8-afeede1d5298.png)

I saw the PR with basic emoji support. We'd just need to define a matchihng emoji for each section adn then implement a toggle to enable/disable them.

Would be a good follow-up PR to #90 I could look into this weekend :wink:

**Comment by dnmanor** [comment]
Hey @ndom91 thats a nice idea lets work on it. Also @katherinepeterson I just noticed the merge conflict but i'm way behind the current repo so I have forked again to avoid rebasing. I will make a PR with the same implementation and hopefully what @ndom91 suggested too.
