### ISSUE TITLE
[FEATURE] Dropdowns Section

### ISSUE THREAD

**Issue by omerayyildiz** [octokatherine/readme.so#85]
For example:

<details>
<summary>What is my problem?</summary>
<br> I don't know LOL </br>
<ul>
     <li>One</li>
     <li>Two</li>
</ul>
</details>

How can you do this? 👆

```html
<details>
<summary>What is my problem?</summary>
<br> I don't know LOL </br>
<ul>
     <li>One</li>
     <li>Two</li>
</ul>
</details>
```

Source: [Dropdowns Gist](https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61)
Thank You, @citrusui! 🤩

**Comment by omerayyildiz** [comment]
How can I link to PR: #86?

**Comment by imadatyatalah** [comment]
it's not working in the preview.
![Screenshot from 2021-04-24 17-15-17](https://user-images.githubusercontent.com/70093484/115967190-b4747680-a520-11eb-9865-1b742b7604d4.png)

**Comment by katherinepeterson** [comment]
What needs to happen to make this render correctly in the preview, is to add styles for those tags inside `styles/globals.css`
